FROM node:22-alpine as builder

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:22-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install -omit-dev
COPY --from=builder /app/dist ./dist
EXPOSE 9000
CMD ["node", "dist/server.js"]